import type {
  FixRecord,
  FlowExecutionResult,
  HumazieFlow,
  HumazieIssue,
  ProductMap,
  RunSummary,
} from "../types.js";

export function renderMarkdownReport(options: {
  summary: RunSummary;
  flows: HumazieFlow[];
  results: FlowExecutionResult[];
  issues: HumazieIssue[];
  fixes: FixRecord[];
  productMap: ProductMap;
  untestedReasons: string[];
}): string {
  const { summary, flows, results, issues, fixes, productMap, untestedReasons } = options;
  const lines: string[] = [];

  lines.push(`# Humazie Review Report`);
  lines.push("");
  lines.push(`## Review Summary`);
  lines.push("");
  lines.push(`| Field | Value |`);
  lines.push(`| --- | --- |`);
  lines.push(`| Run ID | ${summary.runId} |`);
  lines.push(`| Git commit | ${summary.gitCommit} |`);
  lines.push(`| Environment | ${summary.environment} |`);
  lines.push(`| Base URL | ${summary.baseUrl} |`);
  lines.push(`| Mobile | ${summary.mobile} |`);
  lines.push(`| Auto-fix | ${summary.autoFix} |`);
  lines.push(`| Routes / modes reviewed | ${summary.routesReviewed.join(", ") || "—"} |`);
  lines.push(`| Total flows | ${summary.totalFlows} |`);
  lines.push(`| Passed | ${summary.passedFlows} |`);
  lines.push(`| Failed | ${summary.failedFlows} |`);
  lines.push(`| Issues found | ${summary.issuesFound} |`);
  lines.push(`| Issues fixed | ${summary.issuesFixed} |`);
  lines.push(`| Manual review | ${summary.issuesManualReview} |`);
  lines.push(`| Duration | ${Math.round(summary.durationMs / 1000)}s |`);
  lines.push("");

  lines.push(`## User Journeys Tested`);
  lines.push("");
  for (const flow of flows) {
    const result = results.find((r) => r.flowId === flow.id);
    lines.push(`### ${flow.name}`);
    lines.push("");
    lines.push(`- **Goal:** ${flow.userGoal}`);
    lines.push(`- **Actions:** ${flow.actions.map((a) => a.description).join(" → ")}`);
    lines.push(`- **Result:** ${result?.status ?? "not run"}`);
    if (result?.screenshots.length) {
      lines.push(`- **Evidence:** ${result.screenshots.map((s) => `\`${s}\``).join(", ")}`);
    }
    if (result?.tracePath) lines.push(`- **Trace:** \`${result.tracePath}\``);
    const flowIssues = issues.filter((i) => i.flowId === flow.id);
    if (flowIssues.length) {
      lines.push(`- **Problems:** ${flowIssues.map((i) => i.title).join("; ")}`);
    }
    lines.push("");
  }

  lines.push(`## Issues`);
  lines.push("");
  if (issues.length === 0) {
    lines.push("_No issues discovered._");
    lines.push("");
  }
  for (const issue of issues) {
    lines.push(`### ${issue.title}`);
    lines.push("");
    lines.push(`- **Severity:** ${issue.severity}`);
    lines.push(`- **Category:** ${issue.category}`);
    lines.push(`- **Status:** ${issue.status}`);
    lines.push(`- **User impact:** ${issue.userImpact}`);
    lines.push(`- **Expected:** ${issue.expectedBehavior}`);
    lines.push(`- **Actual:** ${issue.actualBehavior}`);
    lines.push(`- **Reproduction:**`);
    for (const step of issue.reproductionSteps) lines.push(`  1. ${step}`);
    if (issue.rootCause) lines.push(`- **Root cause:** ${issue.rootCause}`);
    if (issue.suspectedFiles.length) {
      lines.push(`- **Related files:** ${issue.suspectedFiles.map((f) => `\`${f}\``).join(", ")}`);
    }
    if (issue.screenshots.length) {
      lines.push(`- **Screenshots:** ${issue.screenshots.map((s) => `\`${s}\``).join(", ")}`);
    }
    if (issue.tracePath) lines.push(`- **Trace:** \`${issue.tracePath}\``);
    lines.push("");
  }

  lines.push(`## Automatic Fixes`);
  lines.push("");
  if (fixes.length === 0) {
    lines.push("_No automatic fixes attempted._");
    lines.push("");
  }
  for (const fix of fixes) {
    lines.push(`### Fix for ${fix.issueId}`);
    lines.push("");
    lines.push(`- **Status:** ${fix.status}`);
    lines.push(`- **Summary:** ${fix.summary}`);
    if (fix.branch) lines.push(`- **Branch:** \`${fix.branch}\``);
    if (fix.commit) lines.push(`- **Commit:** \`${fix.commit}\``);
    if (fix.changedFiles.length) {
      lines.push(`- **Files:** ${fix.changedFiles.map((f) => `\`${f}\``).join(", ")}`);
    }
    if (fix.testsAdded.length) {
      lines.push(`- **Tests:** ${fix.testsAdded.join(", ")}`);
    }
    lines.push(`- **Verification:** ${fix.verificationResults.join("; ") || "—"}`);
    lines.push("");
  }

  lines.push(`## Product Map Snapshot`);
  lines.push("");
  lines.push(
    `Nodes: ${productMap.nodes.length}; Edges: ${productMap.edges.length}; Modes: ${productMap.modes.join(", ")}`,
  );
  lines.push("");

  lines.push(`## Remaining Risks`);
  lines.push("");
  for (const reason of untestedReasons) lines.push(`- ${reason}`);
  if (untestedReasons.length === 0) {
    lines.push("- All generated priority flows were attempted.");
  }
  lines.push("");
  lines.push(`_Generated by Humazie Bot_`);
  lines.push("");

  return lines.join("\n");
}
