/**
 * pycrdt <-> Yjs wire interop (ADR-0006 criterion 1), for real this time.
 *
 * The original M9 spike could only assert the Python half of the contract. This
 * takes a Yjs update generated by *pycrdt* (in Python, via
 * `LayerDocument.encode_update`) and applies it to a JavaScript Yjs `Y.Doc`,
 * then reads the exact structure the live editor will bind to: the `tree` map,
 * and a note body as a `Y.Text`. If this passes, the two runtimes genuinely
 * speak the same protocol and the collaborative editor can bind to it.
 *
 * The fixture is a committed constant; regenerate it with:
 *   python -c "from app.infrastructure.crdt.document import LayerDocument; \
 *              from app.domain.collaboration import TreeNode; \
 *              import base64; d=LayerDocument('interop-doc'); \
 *              d.upsert_node(TreeNode(node_id='note-1',name='Hello',is_note=True),body='hello from pycrdt'); \
 *              print(base64.b64encode(d.encode_update()).decode())"
 */

import { describe, expect, it } from "vitest";
import * as Y from "yjs";

// A Yjs update produced by pycrdt (Python), base64-encoded. See the docstring.
const PYCRDT_UPDATE =
  "ARCzvbTqlKbCBgAnAQR0cmVlBm5vdGUtMQEoALO9tOqUpsIGAAZwYXJlbnQBfigAs7206pSmwgYABG5hbWUBdwVIZWxsbygAs7206pSmwgYABW9yZGVyAXcCYTAoALO9tOqUpsIGAAdpc19ub3RlAXgoALO9tOqUpsIGAAdkZWxldGVkAXknAQZib2RpZXMGbm90ZS0xAgQAs7206pSmwgYGEWhlbGxvIGZyb20gcHljcmR0JwEEbWV0YQZub3RlLTEBJwCzvbTqlKbCBhgEdGFncwAnAQR0cmVlCGZvbGRlci0xASgAs7206pSmwgYaBnBhcmVudAF+KACzvbTqlKbCBhoEbmFtZQF3CFJlc2VhcmNoKACzvbTqlKbCBhoFb3JkZXIBdwJhMCgAs7206pSmwgYaB2lzX25vdGUBeSgAs7206pSmwgYaB2RlbGV0ZWQBeQA=";

function decode(b64: string): Uint8Array {
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

describe("pycrdt <-> Yjs interop", () => {
  it("a JS Yjs doc reconstructs a document authored in pycrdt", () => {
    const doc = new Y.Doc();
    Y.applyUpdate(doc, decode(PYCRDT_UPDATE));

    const tree = doc.getMap("tree");
    const note = tree.get("note-1") as Y.Map<unknown>;
    expect(note.get("name")).toBe("Hello");
    expect(note.get("is_note")).toBe(true);

    const folder = tree.get("folder-1") as Y.Map<unknown>;
    expect(folder.get("name")).toBe("Research");
    expect(folder.get("is_note")).toBe(false);

    // The note body is a Y.Text — the exact type the editor binds to CodeMirror.
    const bodies = doc.getMap("bodies");
    const body = bodies.get("note-1") as Y.Text;
    expect(body).toBeInstanceOf(Y.Text);
    expect(body.toJSON()).toBe("hello from pycrdt");
  });

  it("an edit in JS produces an update pycrdt could merge (round-trip shape)", () => {
    const doc = new Y.Doc();
    Y.applyUpdate(doc, decode(PYCRDT_UPDATE));
    const before = Y.encodeStateVector(doc);

    const body = doc.getMap("bodies").get("note-1") as Y.Text;
    body.insert(body.length, " — edited in JS");

    // The incremental update is a standard Yjs binary diff; Python applies the
    // same bytes via LayerDocument.apply_update. We assert it is non-empty and
    // that the local doc reflects the edit.
    const update = Y.encodeStateAsUpdate(doc, before);
    expect(update.byteLength).toBeGreaterThan(0);
    expect(body.toJSON()).toBe("hello from pycrdt — edited in JS");
  });
});
