"""Context export: preview, clipboard, and writing files to disk.

Writing is the only place in Milestone 1 where Strata touches the filesystem
outside the workspace, so it goes through a native save dialog: the *user* picks
the destination, the frontend never supplies a path. That closes the "frontend
asks Python to write anywhere" hole by construction.
"""

from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field
from PySide6.QtCore import QObject, Slot
from PySide6.QtWidgets import QFileDialog

from app.bridge.envelope import bridge_method
from app.domain.errors import CancelledError, InternalError
from app.domain.export import ContentMode, ContextDepth, ExportResult, ExportShape, ExportTarget
from app.infrastructure.logging.logger import get_logger
from app.services.container import Services

logger = get_logger(__name__)


class RenderExportRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    object_ids: list[str] = Field(min_length=1, max_length=2000)
    prompt: str = Field(default="", max_length=32_000)
    target: ExportTarget = "generic"
    shape: ExportShape = "single-file"
    depth: ContextDepth = "selected-only"
    content_mode: ContentMode = "full"
    token_budget: int | None = Field(default=None, ge=500, le=2_000_000)
    # Exporting decrypted private content requires an explicit acknowledgement
    # from the user; the frontend sets this only after the privacy review.
    acknowledge_private: bool = False


class RenderExportResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    result: ExportResult


class WriteExportResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    files_written: int
    directory_name: str
    export_id: str
    private_source_count: int


class ExportBridge(QObject):
    def __init__(self, services: Services, parent: QObject | None = None) -> None:
        super().__init__(parent)
        self._services = services

    def _build(self, request: RenderExportRequest) -> ExportResult:
        plan = self._services.exports.plan(
            object_ids=request.object_ids,
            prompt=request.prompt,
            target=request.target,
            shape=request.shape,
            depth=request.depth,
            content_mode=request.content_mode,
            token_budget=request.token_budget,
        )
        if plan.includes_private_content and not request.acknowledge_private:
            from app.domain.errors import PermissionDeniedError

            raise PermissionDeniedError(
                "This export contains decrypted private content. Confirm the privacy review "
                "before exporting.",
                details={
                    "privateSourceCount": plan.private_source_count,
                    "privateLayers": plan.private_layer_names,
                },
            )
        return self._services.exports.render(plan)

    @Slot(str, result=str)
    @bridge_method(RenderExportRequest)
    def render_export(self, request: RenderExportRequest) -> RenderExportResponse:
        """Render the export in memory so the UI can preview it. Writes nothing."""
        return RenderExportResponse(result=self._build(request))

    @Slot(str, result=str)
    @bridge_method(RenderExportRequest)
    def write_export(self, request: RenderExportRequest) -> WriteExportResponse:
        result = self._build(request)

        directory = QFileDialog.getExistingDirectory(
            None,
            "Choose a folder for the Strata context export",
            str(Path.home()),
        )
        if not directory:
            raise CancelledError("Export cancelled.")

        target_root = Path(directory)
        written = 0
        try:
            for part in result.parts:
                destination = target_root / part.filename
                # part.filename is generated by the export service, never by the
                # frontend, but re-check that it stays inside the chosen folder.
                resolved = destination.resolve()
                if target_root.resolve() not in resolved.parents:
                    raise InternalError("Export path escaped the destination folder.")
                resolved.parent.mkdir(parents=True, exist_ok=True)
                resolved.write_text(part.content, encoding="utf-8", newline="\n")
                written += 1
        except OSError as exc:
            raise InternalError("The export could not be written.") from exc

        logger.info(
            "export.written",
            export_id=result.export_id,
            files=written,
            target=result.target,
            private_sources=result.private_source_count,
        )
        return WriteExportResponse(
            files_written=written,
            directory_name=target_root.name,
            export_id=result.export_id,
            private_source_count=result.private_source_count,
        )
