"""Generate ``app/desktop/webview2/_slots.py`` from the WebView2 SDK header.

A COM interface is a vtable, and a vtable is an *ordered* list of function
pointers. Calling slot 29 when ``ExecuteScript`` is at 30 does not raise, does
not fail a type check and does not return an error — it calls whatever function
sits at that offset with the wrong arguments. In a process that also contains
Chromium, that is a crash at best.

So the slot numbers are not written by hand. This reads Microsoft's own
``WebView2.h``, which declares each interface twice — once as a C++ class and
once as a C-style ``…Vtbl`` struct whose field order *is* the ABI — and emits
the second form as Python constants. Re-run it when the SDK is updated; the
generated file is committed so a normal build needs neither the header nor the
network.

Usage::

    # the header lives in the Microsoft.Web.WebView2 NuGet package, under
    # build/native/include/WebView2.h
    python -m scripts.webview2_slots path/to/WebView2.h

"""

from __future__ import annotations

import re
import sys
from pathlib import Path

OUTPUT = Path(__file__).resolve().parent.parent / "app" / "desktop" / "webview2" / "_slots.py"

# The interfaces the pane actually calls or implements. Kept explicit rather
# than emitting all ~300: an unused constant is a slot number nobody has
# checked against a real call.
INTERFACES = (
    "ICoreWebView2Environment",
    "ICoreWebView2EnvironmentOptions",
    "ICoreWebView2Controller",
    "ICoreWebView2",
    "ICoreWebView2Settings",
    "ICoreWebView2Settings2",
    "ICoreWebView2NavigationStartingEventArgs",
    "ICoreWebView2NavigationCompletedEventArgs",
    "ICoreWebView2NewWindowRequestedEventArgs",
    "ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler",
    "ICoreWebView2CreateCoreWebView2ControllerCompletedHandler",
    "ICoreWebView2ExecuteScriptCompletedHandler",
    "ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler",
    "ICoreWebView2NavigationStartingEventHandler",
    "ICoreWebView2NavigationCompletedEventHandler",
    "ICoreWebView2NewWindowRequestedEventHandler",
    "ICoreWebView2DocumentTitleChangedEventHandler",
    "ICoreWebView2SourceChangedEventHandler",
)


def read_iids(header: str) -> dict[str, str]:
    """``MIDL_INTERFACE("<iid>")`` immediately precedes the interface it names."""
    pairs = re.findall(r'MIDL_INTERFACE\("([0-9a-fA-F-]+)"\)\s*\r?\n\s*(\w+)\s*:\s*public', header)
    return {name: iid for iid, name in pairs}


def read_slots(header: str, interface: str) -> list[str]:
    """Method names in vtable order, from the C-style ``…Vtbl`` struct.

    ``DECLSPEC_XFGVIRT(Iface, Method)`` tags every entry, in declaration order,
    which is exactly the ABI order — including the three inherited IUnknown
    slots and any inherited from a base interface.
    """
    match = re.search(
        r"typedef struct " + interface + r"Vtbl\s*\{(.*?)\n    \} " + interface + r"Vtbl;",
        header,
        re.S,
    )
    if match is None:
        raise SystemExit(f"{interface}: no Vtbl struct in the header")
    entries = re.findall(r"DECLSPEC_XFGVIRT\(\s*(\w+)\s*,\s*(\w+)\s*\)", match.group(1))
    return [method for _, method in entries]


def constant_name(interface: str, method: str) -> str:
    """``ICoreWebView2Controller`` + ``put_Bounds`` -> ``CONTROLLER_PUT_BOUNDS``."""
    stem = interface.removeprefix("ICoreWebView2")
    # The root interface is *just* the prefix, so it has no stem of its own.
    prefix = re.sub(r"(?<!^)(?=[A-Z])", "_", stem).upper().strip("_") if stem else "WEBVIEW"
    return f"{prefix}_{method.upper()}"


def read_target_version(options_header: str) -> str:
    """The runtime version this SDK declares itself compatible with.

    Not cosmetic. ``ICoreWebView2EnvironmentOptions`` must report a parseable
    version from ``get_TargetCompatibleBrowserVersion``; the SDK's own C++
    helper seeds it from this define, and environment creation answers
    ``E_INVALIDARG`` for an empty one.
    """
    match = re.search(r'CORE_WEBVIEW_TARGET_PRODUCT_VERSION\s+L"([\d.]+)"', options_header)
    return match.group(1) if match else ""


def render(header: str, options_header: str) -> str:
    iids = read_iids(header)
    version = read_target_version(options_header)
    lines = [
        '"""Vtable slot numbers and IIDs for the WebView2 interfaces Strata calls.',
        "",
        "GENERATED by ``scripts/webview2_slots.py`` from Microsoft's ``WebView2.h``.",
        "Do not edit by hand — see that script for why these must not be transcribed.",
        '"""',
        "",
        "# ruff: noqa: E501  (generated: some SDK interface names are simply long)",
        "",
        "",
        "from __future__ import annotations",
        "",
        "# What ICoreWebView2EnvironmentOptions must report as its compatible",
        "# version. Creation fails with E_INVALIDARG if this is empty.",
        f'TARGET_COMPATIBLE_BROWSER_VERSION = "{version}"',
        "",
    ]
    for interface in INTERFACES:
        slots = read_slots(header, interface)
        iid = iids.get(interface)
        lines.append(f"# --- {interface} " + "-" * max(0, 66 - len(interface)))
        if iid:
            lines.append(f'IID_{constant_name(interface, "x").removesuffix("_X")} = "{iid}"')
        for index, method in enumerate(slots):
            if method in ("QueryInterface", "AddRef", "Release"):
                continue  # IUnknown is handled by com.Interface itself
            lines.append(f"{constant_name(interface, method)} = {index}")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    main_header = Path(sys.argv[1])
    header = main_header.read_text(encoding="utf-8", errors="replace")
    # Shipped beside WebView2.h in the same NuGet package; it carries the
    # compatible-version define and nothing else we need.
    options = main_header.with_name("WebView2EnvironmentOptions.h")
    if not options.is_file():
        raise SystemExit(f"expected {options.name} beside {main_header.name}")
    OUTPUT.write_text(
        render(header, options.read_text(encoding="utf-8", errors="replace")), encoding="utf-8"
    )
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
